/**
 * Sinônimos e gírias (dobrados: minúsculos e sem acento) para as categorias PADRÃO, além das
 * `keywords` que cada categoria já tem. Só valem se a categoria com esse ID existir e não estiver arquivada.
 */
import { CATEGORY_IDS } from '@/domain/defaults';

export const CATEGORY_SYNONYMS: Record<string, string[]> = {
  [CATEGORY_IDS.restaurantes]: [
    'restaurante',
    'comida fora',
    'comer fora',
    'comi fora',
    'ifood',
    'i food',
    'pizzaria',
    'hamburgueria',
    'mcdonalds',
    'mc donalds',
    'mequi',
    'burger king',
    'subway',
    'outback',
    'acai',
    'sorvete',
    'cerveja',
    'chopp',
    'happy hour',
    'boteco',
    'churrascaria',
    'almocei',
    'jantei',
    'lanchei',
    'marmita',
    'quentinha',
    'self service',
    'cafeteria',
    'starbucks',
    'pastel',
    'esfiha',
    'habibs',
    'japones',
    'temaki',
    'refeicao',
    'ze delivery',
    'cafezinho',
    'salgado',
    'coxinha',
    'padoca',
    'food',
  ],
  [CATEGORY_IDS.mercado]: [
    'supermercado',
    'mercadinho',
    'sacolao',
    'atacado',
    'atacadista',
    'rancho',
    'mercearia',
    'emporio',
    'hortifruti',
    'feira',
    'pao',
    'paes',
    'leite',
    'frutas',
    'verduras',
    'carne',
    'compras do mes',
    'compra do mes',
    'guanabara',
    'zaffari',
    'makro',
    'tenda',
    'oba',
  ],
  [CATEGORY_IDS.transporte]: [
    'gasolina',
    'combustivel',
    'alcool',
    'diesel',
    'gnv',
    'abastecer',
    'abasteci',
    'abastecimento',
    'posto',
    'shell',
    'ipiranga',
    '99pop',
    '99 pop',
    'cabify',
    'indrive',
    'trem',
    'brt',
    'bilhete unico',
    'zona azul',
    'sem parar',
    'conectcar',
    'pneu',
    'troca de oleo',
    'revisao do carro',
    'lava jato',
    'lavagem do carro',
    'licenciamento',
    'carro',
    'moto',
    'patinete',
    'corrida',
  ],
  [CATEGORY_IDS.moradia]: [
    'aluguel',
    'condominio',
    'moveis',
    'faxina',
    'diarista',
    'empregada',
    'material de construcao',
    'leroy',
    'encanador',
    'eletricista',
    'conserto',
    'mudanca',
  ],
  [CATEGORY_IDS.contas]: [
    'conta de luz',
    'conta de agua',
    'conta de gas',
    'conta de internet',
    'conta do celular',
    'conta de telefone',
    'botijao',
    'wifi',
    'wi fi',
    'recarga',
    'plano do celular',
    'tv a cabo',
    'net',
    'contas',
  ],
  [CATEGORY_IDS.saude]: [
    'drogasil',
    'raia',
    'droga raia',
    'pague menos',
    'remedios',
    'medicamento',
    'medicamentos',
    'exames',
    'convenio',
    'unimed',
    'amil',
    'hapvida',
    'fisioterapia',
    'oculos',
    'otica',
    'vacina',
    'laboratorio',
    'saude',
  ],
  [CATEGORY_IDS.educacao]: [
    'cursos',
    'livros',
    'mensalidade escolar',
    'ingles',
    'idiomas',
    'pos graduacao',
    'mba',
    'apostila',
    'colegio',
    'creche',
    'aula',
    'aulas',
  ],
  [CATEGORY_IDS.impostos]: [
    'impostos',
    'tarifa bancaria',
    'iof',
    'imposto de renda',
    'das',
    'mei',
    'inss',
    'taxas',
  ],
  [CATEGORY_IDS.lazer]: [
    'balada',
    'pousada',
    'airbnb',
    'praia',
    'museu',
    'futebol',
    'estadio',
    'diversao',
    'boliche',
    'karaoke',
    'role',
    'passagem aerea',
    'passagens aereas',
    'steam',
    'jogos',
    'viajar',
    'ferias',
  ],
  [CATEGORY_IDS.compras]: [
    'roupas',
    'sapatos',
    'camisa',
    'camiseta',
    'calca',
    'vestido',
    'bolsa',
    'shein',
    'aliexpress',
    'magazine luiza',
    'americanas',
    'casas bahia',
    'renner',
    'riachuelo',
    'zara',
    'eletronicos',
    'tv',
    'televisao',
    'notebook',
    'computador',
    'tablet',
    'fone',
    'videogame',
    'playstation',
    'xbox',
    'geladeira',
    'fogao',
    'microondas',
    'maquina de lavar',
    'eletrodomestico',
    'smartphone',
    'iphone',
    'relogio',
    'compra online',
  ],
  [CATEGORY_IDS.assinaturas]: [
    'assinaturas',
    'amazon prime',
    'disney plus',
    'disney+',
    'smart fit',
    'smartfit',
    'deezer',
    'apple music',
    'paramount',
    'crunchyroll',
    'chatgpt',
    'streaming',
    'game pass',
    'xbox game pass',
    'ps plus',
    'mensalidade da academia',
  ],
  [CATEGORY_IDS.cuidados]: [
    'salao de beleza',
    'cabeleireiro',
    'barbeiro',
    'unha',
    'unhas',
    'cosmeticos',
    'maquiagem',
    'depilacao',
    'sobrancelha',
    'skincare',
    'boticario',
    'natura',
    'sephora',
  ],
  [CATEGORY_IDS.pets]: ['vet', 'pet shop', 'cachorro', 'gato', 'petz', 'cobasi', 'pets'],
  [CATEGORY_IDS.doacoes]: ['doacoes', 'doei', 'igreja'],
  [CATEGORY_IDS.investimentos]: [
    'investimentos',
    'investi',
    'tesouro direto',
    'lci',
    'lca',
    'fiis',
    'cripto',
    'bitcoin',
    'reserva de emergencia',
  ],
  [CATEGORY_IDS.dividas]: [
    'dividas',
    'emprestimos',
    'cheque especial',
    'agiota',
    'renegociacao',
    'parcela do carro',
    'parcela do apartamento',
  ],
  [CATEGORY_IDS.salario]: [
    'contracheque',
    'pro labore',
    'prolabore',
    'bonus',
    'vale alimentacao',
    'vale refeicao',
  ],
  [CATEGORY_IDS.rendaExtra]: [
    'freelas',
    'bicos',
    'renda extra',
    'vendi',
    'vendas',
    'job',
    'consultoria',
    'aula particular',
    'uber',
    'hora extra',
    'horas extras',
    'trampo',
  ],
  [CATEGORY_IDS.rendimentos]: ['rendimentos', 'dividendos', 'aluguel', 'jcp', 'proventos', 'rendeu', 'juros'],
  [CATEGORY_IDS.reembolso]: [
    'ressarcimento',
    'restituicao do imposto',
    'reembolsos',
    'estornaram',
    'devolveram',
  ],
  [CATEGORY_IDS.outrosReceita]: ['heranca', 'mesada', 'loteria', 'sorteio', 'pix'],
};

/** Itens que, junto de um verbo de compra ("comprei", "comprar"), indicam a categoria Compras. */
export const PURCHASE_ITEMS = [
  'celular',
  'telefone',
  'smartphone',
  'iphone',
  'tv',
  'televisao',
  'notebook',
  'computador',
  'tablet',
  'fone',
  'geladeira',
  'fogao',
  'roupa',
  'tenis',
  'sapato',
  'presente',
  'videogame',
  'relogio',
  'oculos',
  'movel',
  'moveis',
  'sofa',
  'cama',
];

export const PURCHASE_VERB =
  /\b(comprei|comprar|compra|comprou|compramos|comprando|parcelei|adquiri|comprado)\b/;
